server:
  port: 8080
spring:
  application:
    name: "customer"
  datasource:
    url: jdbc:mysql://localhost:3306/customersdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://localhost:8071/"