build:
  version: "1.0"

customer:
  message: "Customer Demo related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "example@gmail.com"
  onCallSupport:
    - (000) 000-0000
    - (111) 111-1111